const ANNOTATION_CDS_WEBSOCKET = "@cds.websocket";

export const ANNOTATION_CDS_WEBSOCKET_ENABLED = `${ANNOTATION_CDS_WEBSOCKET}.enabled`;
export const ANNOTATION_CDS_WEBSOCKET_INBOUND = `${ANNOTATION_CDS_WEBSOCKET}.inbound`;
export const ANNOTATION_CDS_WEBSOCKET_OUTBOUND = `${ANNOTATION_CDS_WEBSOCKET}.outbound`;
export const ANNOTATION_CDS_WEBSOCKET_TARGET = `${ANNOTATION_CDS_WEBSOCKET}.target`;